export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const TOGGLE_LOGIN = 'TOGGLE_LOGIN'
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const SHOW_ALERT = 'SHOW_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';
export const USER_DATA_LOADED = 'USER_DATA_LOADED';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const UPDATE_USER = 'UPDATE_USER';


export const CATEGORY_LOAD_SUCCESS = 'CATEGORY_LOAD_SUCCESS';
export const CATEGORY_LOAD_FAILED = 'CATEGORY_LOAD_FAILED';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const GET_SINGLE_CATEGORY_SUCCESS = 'GET_SINGLE_CATEGORY_SUCCESS'
export const GET_SINGLE_CATEGORY_FAILED = 'GET_SINGLE_CATEGORY_FAILED'
export const DELETE_SINGLE_CATEGORY_SUCCESS = 'DELETE_SINGLE_CATEGORY_SUCCESS'
export const DELETE_SINGLE_CATEGORY_FAILED = 'DELETE_SINGLE_CATEGORY_FAILED'



